/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_GUI;

import dbconnection.dbconnection;
import dbconnection.dbconnection2;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;
import sms_Classes.NewAccDetail;
import sms_Classes.RanNo;

/**
 *
 * @author Dulan
 */
public class NewAcc extends javax.swing.JInternalFrame {

    /**
     * Creates new form About
     */
    String sql,sql1;
    PreparedStatement ps;
    ResultSet rs;
    int a = 5;
    int b = 5;
    
    public NewAcc() {
        initComponents();      
        mainFun();
        
    }
    
    void mainFun(){
        Random rand = new Random(); 
            int rand_int1 = rand.nextInt(1000000000); 
            int r = String.valueOf(rand_int1).length();
            while(r!=8){
                rand_int1 = rand.nextInt(100000000); 
                r = String.valueOf(rand_int1).length();
            }           
            sqlFun(rand_int1);
    }
    
    void sqlFun(int r){
            try{
                sql = "SELECT COUNT(idNo) FROM AccNo WHERE AccNo="+r+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    a = rs.getInt("COUNT(idNo)");
                }
                if(a==1){
                    mainFun();
                }
                else if(a==0){
                    accTF.setText(r+"");
                }
                else{
                    mainFun();
                }
                
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            }
    }
    
    void sqlFun1(String x, String y){
            try{
                System.out.println(b +" start");
                System.out.println(x);
                System.out.println(y);
                sql1 = "SELECT COUNT(idNo) FROM AccNo WHERE name='"+x+"' OR email='"+y+"'";
                ps = dbconnection2.getConnection().prepareStatement(sql1);
                rs = ps.executeQuery();
                System.out.println("=================Starting of loop=================");
                while(rs.next()){
                    b = rs.getInt("COUNT(idNo)");
                    System.out.println(rs.getInt("COUNT(idNo)"));
                    System.out.println(b);
                }
                if(b==1){
                    System.out.println("true");
                    JOptionPane.showMessageDialog(null,"There is already an Account on this email or username!!!");
                }
                else if(a==0){
                    System.out.println("false1");
                    //accTF.setText(r+"");
                    insert();
                }
                else{
                    System.out.println("false2");
                    //mainFun();
                    JOptionPane.showMessageDialog(null,"A Error has occured!!!");
                }
                System.out.println("=================SQL=================");
                System.out.println(sql1);
                System.out.println("=================next loop=================");
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            }
    }
    
    void insert(){
        try{
                String n = nTF.getText();
                String a = accTF.getText();
                String p = passPF.getText();
                String e = eTF.getText();
                sql1 = "INSERT INTO AccNo (Name, AccNo, PassID, email, moneyLeft) VALUES "
                        + "('"+n+"', "+a+", '"+p+"','"+e+"',"+25000+");";
                ps = dbconnection2.getConnection().prepareStatement(sql1);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"A new Account is created \n"
                        + "this account will be activated in around 24h \n"
                        + "thanks for using Knight's bank");
                
            }
            catch (SQLException ex) {
                ex.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passPF = new javax.swing.JPasswordField();
        accTF = new javax.swing.JTextField();
        nTF = new javax.swing.JTextField();
        eTF = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Create new Account");
        setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        jButton1.setText("Create new Acc.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel3.setText("AccNo");

        jLabel4.setText("PassID");

        jLabel5.setText("Email");

        passPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPFActionPerformed(evt);
            }
        });

        accTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTFActionPerformed(evt);
            }
        });

        nTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTFActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nTF)
                    .addComponent(passPF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Add Account");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTFActionPerformed

    private void accTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accTFActionPerformed

    private void passPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nTF.getText();
        String pass = passPF.getText();
        int a = Integer.parseInt(accTF.getText());
        String e = eTF.getText();
        sqlFun1(name,e);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewAccDetail an = new NewAccDetail();
        an.newDetail();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField accTF;
    private javax.swing.JTextField eTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nTF;
    private javax.swing.JPasswordField passPF;
    // End of variables declaration//GEN-END:variables
}
