/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_GUI;

import dbconnection.dbconnection2;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Dulan
 */
public class TransWin extends javax.swing.JInternalFrame {

    String s;
    String sql,sql1,sql3;
    PreparedStatement ps,ps1,ps2;
    ResultSet rs,rs1,rs2;
    int q,w;
    /**
     * Creates new form About
     */
    public TransWin() {
        initComponents();
        constructForTime();
        constructForDate();
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fromTF = new javax.swing.JTextField();
        amTF = new javax.swing.JTextField();
        toTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accnoLBL = new javax.swing.JLabel();
        accno1LBL = new javax.swing.JLabel();
        noLBL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setClosable(true);
        setTitle("Trans Window");
        setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setText("Knight's Service");

        fromTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        fromTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromTFActionPerformed(evt);
            }
        });
        fromTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fromTFKeyReleased(evt);
            }
        });

        amTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        amTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amTFKeyReleased(evt);
            }
        });

        toTF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        toTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                toTFKeyReleased(evt);
            }
        });

        jLabel2.setText("Sender's Id");

        jLabel3.setText("Amount");

        jLabel4.setText("R'eceiver's ID");

        accnoLBL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        accno1LBL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        noLBL.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Complete the trasaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Rs.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(3, 3, 3)
                                        .addComponent(amTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(noLBL)
                                        .addGap(46, 46, 46))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fromTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accnoLBL)
                                    .addComponent(accno1LBL)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)
                                .addComponent(jLabel7))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(accnoLBL))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(noLBL)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(accno1LBL))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromTFActionPerformed

    private void amTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amTFKeyReleased
        sendDetail();
    }//GEN-LAST:event_amTFKeyReleased

    private void fromTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromTFKeyReleased
        accDetail1();
        common();
    }//GEN-LAST:event_fromTFKeyReleased

    private void toTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toTFKeyReleased
        accDetail2();
        common();
    }//GEN-LAST:event_toTFKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        comp1();
        comp2();
        comp();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accno1LBL;
    private javax.swing.JLabel accnoLBL;
    private javax.swing.JTextField amTF;
    private javax.swing.JTextField fromTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel noLBL;
    private javax.swing.JTextField toTF;
    // End of variables declaration//GEN-END:variables

    private void sendDetail() {
        String a = fromTF.getText();
        int b = Integer.parseInt(amTF.getText());
        if(b==0){
            JOptionPane.showMessageDialog(null,"Plz entry money");
        }
        else{
            try{
                sql = "SELECT AccNo, moneyLeft FROM AccNo WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    q =(rs.getInt("moneyLeft"));
                }
                if(b<=q){
                    noLBL.setText("✅");
                }
                else if(b>q){
                    noLBL.setText("❌");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Something went wrong!!!");
                }
            }
            catch (SQLException ex) {
                    ex.printStackTrace();
            }
        }
        
    }
    
    private String constructForDate(){
            final DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
            int interval = 1000; // 1000 ms

            new Timer(interval, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar now = Calendar.getInstance();
                    jLabel7.setText(dateFormat.format(now.getTime()));
                }
                }).start();
            return s;
    }
    
    private String constructForTime(){
            final DateFormat dateFormat = new SimpleDateFormat("HH:mm:ss");
            int interval = 1000; // 1000 ms

            new Timer(interval, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar now = Calendar.getInstance();
                    jLabel6.setText((dateFormat.format(now.getTime())));
                }
                }).start();
            return s;
    }

    private void accDetail1() {
         String a = fromTF.getText();
            try{
                sql = "SELECT COUNT(AccNo) FROM AccNo WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    w =(rs.getInt("COUNT(AccNo)"));
                }
                if(w==1){
                    accnoLBL.setText("✅");
                }
                else if(w==0){
                    accnoLBL.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Something went wrong!!!");
                }
            }
            catch (SQLException ex) {
                    ex.printStackTrace();
            }
        
    }

    private void accDetail2() {
        String a = toTF.getText();
            try{
                sql = "SELECT COUNT(AccNo) FROM AccNo WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    w =(rs.getInt("COUNT(AccNo)"));
                }
                if(w==1){
                    accno1LBL.setText("✅");
                }
                else if(w==0){
                    accno1LBL.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Something went wrong!!!");
                }
            }
            catch (SQLException ex) {
                    ex.printStackTrace();
            }
    }

    private void common() {
        String a = toTF.getText();
        String b = fromTF.getText();
        if(a.equals(b)){
            JOptionPane.showMessageDialog(null,"Both are the same account!!!");
        }
    }

    private void comp() {
        String z = jLabel7.getText();
        String x = jLabel6.getText();
        int a = Integer.parseInt(fromTF.getText());
        int b = Integer.parseInt(amTF.getText());
        int c = Integer.parseInt(toTF.getText());
        sql = "INSERT INTO tranDetail (FromID, ToID, Amount, Date, Time) VALUE("+a
                +","+c
                +","+b
                +","+z
                +",'"+x
                +"')";
        System.out.println(sql);
        try {
            ps = dbconnection2.getConnection().prepareStatement(sql);
            ps.executeUpdate();
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }

    private void comp1() {
        int c ;
        int b = Integer.parseInt(amTF.getText());
        String a = fromTF.getText();
            try{
                sql = "SELECT moneyLeft FROM AccNo WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    w =(rs.getInt("moneyLeft"));
                }
                c = w - b;
                sql = "UPDATE AccNo SET moneyLeft = "+c+" WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                ps.executeUpdate();
            }
            catch (SQLException ex) {
                    ex.printStackTrace();
            }
    }

    private void comp2() {
        int c ;
        int b = Integer.parseInt(amTF.getText());
        String a = toTF.getText();
            try{
                sql = "SELECT moneyLeft FROM AccNo WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                rs = ps.executeQuery();
                while(rs.next()){
                    w =(rs.getInt("moneyLeft"));
                }
                c = w + b;
                sql = "UPDATE AccNo SET moneyLeft = "+c+" WHERE AccNo="+a+"";
                ps = dbconnection2.getConnection().prepareStatement(sql);
                ps.executeUpdate();
            }
            catch (SQLException ex) {
                    ex.printStackTrace();
            }
    }
}
