/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolproject30;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 12a10
 */
public class myMySql extends javax.swing.JFrame {
     Connection cn;
    Statement stmt;
    ResultSet rs;
    String sql,s,d;
    /**
     * Creates new form updateCab
     */
     //DefaultTableModel dtm=new DefaultTableModel();
    ResultSetMetaData rsMetaData;
    int tblNumRows=0, tblNumCols=0, rsNumRows=0, rsNumCols=0;
    String tblColName;
    DefaultTableModel dtm;
    /**
     * Creates new form myMySql
     */
    public myMySql() {
        initComponents();
        dtm=(DefaultTableModel)jTable1.getModel();
        try{
            
          
    
   
        }
        catch(Exception ex){
            //JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exTF = new javax.swing.JTextField();
        exBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exBTN.setText("EXECUTE");
        exBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exBTNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("MY MYSQL");

        jLabel2.setText("HISTORY");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setText("NAME OF DATABASE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(exTF)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(193, 193, 193)
                                        .addComponent(exBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(237, 237, 237)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exTF, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exBTN)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exBTNActionPerformed
jTextArea1.setText(exTF.getText());
        d=DB.getText();
        s=exTF.getText().toString();
         try{
            
          
      cn=DriverManager.getConnection("jdbc:mysql://localhost/"+d+"", "root", "");            
            stmt=cn.createStatement();
            
           
        
            rs=stmt.executeQuery(s);
            
            rsMetaData=rs.getMetaData();
            rsNumRows=rs.getRow();
            rsNumCols=rsMetaData.getColumnCount();
            //JOptionPane.showMessageDialog(null,rsNumCols);
            
            dtm.setColumnCount(rsNumCols);
            
           for(int i=0; i<rsNumCols; i++){                      
                //JOptionPane.showMessageDialog(null,rsMetaData.getColumnName(i));
               jTable1.getTableHeader().getColumnModel().getColumn(i).setHeaderValue(rsMetaData.getColumnName(i+1)+"---");
               JOptionPane.showMessageDialog(null,rsMetaData.getColumnName(i+1));
           }
            fillJTable2();
        }
        catch(Exception ex){
            //JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }
        
 


    }//GEN-LAST:event_exBTNActionPerformed

    /**
     * @param args the command line arguments
     */
      void fillJTable(){
        try{
            //sql="SELECT * FROM t1";
           sql="SELECT * FROM vRegister";
           
            rs=stmt.executeQuery(sql);   
            
            //dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0); //remove all existing rows from the jTable
            while(rs.next()){ 
            //// JOptionPane.showMessageDialog(null,rs.getString("source"));
          
            dtm.addRow(new Object[]{rs.getString("VEHICLENAME"), rs.getString("VEHICLENO"), rs.getString("SEATER"), rs.getString("LUGGAGESTORAGE"), rs.getString("OVERCAR"), rs.getString("VEHICLECOLOR"), rs.getString("SOURCE")});                
            }
        }catch(Exception ex){
            ex.printStackTrace();
        } 
      }
      
      
      void fillJTable1(){
        try{
            //sql="SELECT * FROM t1";
              sql="SELECT * FROM vRegister";
            rs=stmt.executeQuery(sql);   
            
            //dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0); //remove all existing rows from the jTable
            while(rs.next()){ 
            //// JOptionPane.showMessageDialog(null,rs.getString("source"));
           
            ArrayList<String> names = new ArrayList<String>();
            
            names.add(rs.getString("VEHICLENAME"));
            names.add(rs.getString("VEHICLENAME"));
            names.add(rs.getString("VEHICLENO"));
            names.add(rs.getString("SEATER"));
            names.add(rs.getString("LUGGAGESTORAGE"));
            names.add(rs.getString("OVERCAR"));
            names.add(rs.getString("VEHICLECOLOR"));
            
           
            
       
            
            
            
            }
            
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        } 
      }
         void fillJTable2(){
        try{
            //sql="SELECT * FROM t1";
           sql="SELECT * FROM vRegister";
           
            rs=stmt.executeQuery(sql);   
            
            //dtm=(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0); //remove all existing rows from the jTable
            while(rs.next()){ 
            //// JOptionPane.showMessageDialog(null,rs.getString("source"));
          
            Object[] obj = new Object[]{rs.getString("VEHICLENAME"), rs.getString("VEHICLENO"), rs.getString("SEATER"), rs.getString("LUGGAGESTORAGE"), rs.getString("OVERCAR"), rs.getString("VEHICLECOLOR"), rs.getString("SOURCE")};                
            
            
            dtm.addRow(obj);
             
//  ArrayList<Object> temp = new ArrayList<Object>(Arrays.asList(obj));
            }
        }catch(Exception ex){
            ex.printStackTrace();
        } 
      }
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myMySql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myMySql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myMySql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myMySql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myMySql().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DB;
    private javax.swing.JButton exBTN;
    private javax.swing.JTextField exTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
